### ISSUE TITLE
Target framework "netstandard2.0" does not build with error `The name 'Registry' does not exist in the current context`

### ISSUE THREAD

**Issue by o-l-a-v** [PowerShell/PSResourceGet#1779]
### Prerequisites

- [x] Write a descriptive title.
- [x] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/Microsoft.PowerShell.PSResourceGet)
- [x] Search the existing issues.

### Steps to reproduce

* Clone repo
* `& '.\build.ps1' -BuildConfiguration 'Debug' -BuildFramework 'netstandard2.0' -Build -Clean`

Results in:

`error CS0103: The name 'Registry' does not exist in the current context [D:\Git\personal\PowerShell--PSResourceGet\src\code\Microsoft.PowerShell.PSResourceGet.csproj::TargetFramework=netstandard2.0]`

### Expected behavior

```console
Should build
```

### Actual behavior

```console
Does not build
```

### Error details

```console

```

### Environment data

```powershell
Windows 11 24H2 x64
PowerShell v7.4.6
```

### Visuals

<img width="913" alt="Image" src="https://github.com/user-attachments/assets/f95aff94-2c7d-430b-93fc-97eb3be339f9" />

**Comment by o-l-a-v** [comment]
It does not seem that CI/CD builds `netstandard2.0`, only `net472`.

* <https://github.com/search?q=repo%3APowerShell%2FPSResourceGet+path%3A%2F%5E%28%5C.ci%5C%2F%7C%5C.github%5C%2F%29%2F++build.ps1&type=code>

**Comment by anamnavi** [comment]
@o-l-a-v thanks for bringing this up. We used to build on netstandard2.0 and had to move to building on net472 to use some assemblies not available to us in netstandard2.0. Our work item here is to clean up the build script so that it's clear we don't build for netstandard2.0.
